# Generated by Django 5.2.12 on 2026-05-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('AUDITOR', 'Auditor'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20, verbose_name='Rol en el Sistema'),
        ),
    ]
