# Generated by Django 5.2.12 on 2026-05-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='usuario',
        ),
    ]
