# Generated by Django 5.2.12 on 2026-06-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de Restablecimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación del Código'),
        ),
    ]
