# Generated by Django 5.2.12 on 2026-05-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_bien_tasa_bcv_compra_bien_valor_adquisicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('bien_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.bien')),
                ('direccion_completa', models.TextField(verbose_name='Dirección Completa')),
                ('registro_propiedad', models.CharField(max_length=150, unique=True, verbose_name='Registro de Propiedad / Tomo / Folio')),
                ('area_terreno', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Área del Terreno (m²)')),
                ('area_construccion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Área de Construcción (m²)')),
                ('catastro', models.CharField(max_length=100, unique=True, verbose_name='Ficha Catastral / Número de Catastro')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'db_table': 'inmueble',
            },
            bases=('inventario.bien',),
        ),
    ]
