# Generated by Django 5.2.12 on 2026-05-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_bien_tasa_bcv_compra_bien_valor_adquisicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automotor',
            fields=[
                ('bien_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.bien')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa del Vehículo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('año', models.IntegerField(verbose_name='Año de Fabricación')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('serial_motor', models.CharField(max_length=100, unique=True, verbose_name='Serial del Motor')),
                ('serial_carroceria', models.CharField(max_length=100, unique=True, verbose_name='Serial de Carrocería')),
            ],
            options={
                'verbose_name': 'Automotor',
                'verbose_name_plural': 'Automotores',
                'db_table': 'automotor',
            },
            bases=('inventario.bien',),
        ),
    ]
