# Generated by Django 5.2.12 on 2026-05-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automotor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automotor',
            old_name='año',
            new_name='anio',
        ),
    ]
