# Generated by Django 5.2.12 on 2026-09-24 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_logacceso'),
        ('inventario', '0012_bien_fecha_adquisicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del Hallazgo')),
                ('gravedad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=15)),
                ('fecha_deteccion', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Detección')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('observaciones_resolucion', models.TextField(blank=True, null=True, verbose_name='Observaciones de Resolución')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='inventario.bien')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos_reportados', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hallazgo de Auditoría',
                'verbose_name_plural': 'Hallazgos de Auditoría',
                'ordering': ['-fecha_deteccion', '-id'],
            },
        ),
    ]
