--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12
-- Dumped by pg_dump version 15.12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auditoria_logbien; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auditoria_logbien (
    id bigint NOT NULL,
    accion character varying(50) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    detalles text,
    bien_id bigint NOT NULL,
    usuario_id bigint
);


ALTER TABLE public.auditoria_logbien OWNER TO postgres;

--
-- Name: auditoria_logbien_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auditoria_logbien ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_logbien_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: automotor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.automotor (
    bien_ptr_id bigint NOT NULL,
    placa character varying(20) NOT NULL,
    marca character varying(50) NOT NULL,
    modelo character varying(50) NOT NULL,
    anio integer NOT NULL,
    color character varying(30) NOT NULL,
    serial_motor character varying(100) NOT NULL,
    serial_carroceria character varying(100) NOT NULL
);


ALTER TABLE public.automotor OWNER TO postgres;

--
-- Name: usuario_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.usuario_groups OWNER TO postgres;

--
-- Name: custom_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    cedula character varying(20) NOT NULL,
    cargo character varying(100),
    rol character varying(20) NOT NULL,
    unidad_pertenencia_id bigint,
    reset_code character varying(6),
    reset_code_created_at timestamp with time zone
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: custom_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.usuario_user_permissions OWNER TO postgres;

--
-- Name: custom_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: inmueble; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inmueble (
    bien_ptr_id bigint NOT NULL,
    direccion_completa text NOT NULL,
    registro_propiedad character varying(150) NOT NULL,
    area_terreno numeric(12,2) NOT NULL,
    area_construccion numeric(12,2) NOT NULL,
    catastro character varying(100) NOT NULL
);


ALTER TABLE public.inmueble OWNER TO postgres;

--
-- Name: inventario_area; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario_area (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    sede_id bigint NOT NULL
);


ALTER TABLE public.inventario_area OWNER TO postgres;

--
-- Name: inventario_area_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventario_area ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_area_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_asignacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario_asignacion (
    id bigint NOT NULL,
    fecha_asignacion timestamp with time zone NOT NULL,
    activa boolean NOT NULL,
    area_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    bien_id bigint NOT NULL
);


ALTER TABLE public.inventario_asignacion OWNER TO postgres;

--
-- Name: inventario_asignacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventario_asignacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_asignacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_bien; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario_bien (
    id bigint NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text NOT NULL,
    serial_fabrica character varying(100),
    codigo_inventario character varying(50) NOT NULL,
    estado character varying(20) NOT NULL,
    orden_compra_id bigint,
    sede_id bigint NOT NULL,
    tasa_bcv_compra numeric(10,4) NOT NULL,
    valor_adquisicion numeric(12,2) NOT NULL,
    valor_adquisicion_bs numeric(15,2) NOT NULL
);


ALTER TABLE public.inventario_bien OWNER TO postgres;

--
-- Name: inventario_bien_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventario_bien ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_bien_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_mantenimientobien; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario_mantenimientobien (
    id bigint NOT NULL,
    numero_ficha character varying(50) NOT NULL,
    fecha_ficha date NOT NULL,
    tipo_mantenimiento character varying(20) NOT NULL,
    actividad_realizada text NOT NULL,
    materiales_empleados text,
    numero_factura character varying(100) NOT NULL,
    costo numeric(12,2) NOT NULL,
    fecha_mantenimiento date NOT NULL,
    nota text,
    reparado_por character varying(150) NOT NULL,
    conformado_por character varying(150) NOT NULL,
    responsable_administrativo character varying(150) NOT NULL,
    bien_id bigint NOT NULL
);


ALTER TABLE public.inventario_mantenimientobien OWNER TO postgres;

--
-- Name: inventario_mantenimientobien_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventario_mantenimientobien ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_mantenimientobien_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_ordencompra; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario_ordencompra (
    id bigint NOT NULL,
    numero_orden character varying(50) NOT NULL,
    fecha_llegada date NOT NULL,
    conformidad_recepcion boolean NOT NULL,
    archivo_documento character varying(100),
    proveedor character varying(150) NOT NULL
);


ALTER TABLE public.inventario_ordencompra OWNER TO postgres;

--
-- Name: inventario_ordencompra_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventario_ordencompra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_ordencompra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_sede; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario_sede (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.inventario_sede OWNER TO postgres;

--
-- Name: inventario_sede_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventario_sede ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_sede_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_trazabilidadmovimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario_trazabilidadmovimientos (
    id bigint NOT NULL,
    tipo_movimiento character varying(30) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    motivo text,
    area_destino_id bigint,
    area_origen_id bigint,
    bien_id bigint NOT NULL,
    sede_destino_id bigint,
    sede_origen_id bigint,
    usuario_destino_id bigint,
    usuario_origen_id bigint,
    usuario_responsable_id bigint
);


ALTER TABLE public.inventario_trazabilidadmovimientos OWNER TO postgres;

--
-- Name: inventario_trazabilidadmovimientos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventario_trazabilidadmovimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_trazabilidadmovimientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: log_acceso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.log_acceso (
    id bigint NOT NULL,
    ip_address inet NOT NULL,
    accion character varying(100) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    detalles text,
    usuario_id bigint
);


ALTER TABLE public.log_acceso OWNER TO postgres;

--
-- Name: log_acceso_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.log_acceso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_acceso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auditoria_logbien; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auditoria_logbien (id, accion, fecha, detalles, bien_id, usuario_id) FROM stdin;
1	CREACION	2026-07-30 09:58:07.70324-04	El bien hhhh ha sido registrado en el sistema.	9	\N
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Usuario del Sistema	6	add_customuser
22	Can change Usuario del Sistema	6	change_customuser
23	Can delete Usuario del Sistema	6	delete_customuser
24	Can view Usuario del Sistema	6	view_customuser
25	Can add Área	7	add_area
26	Can change Área	7	change_area
27	Can delete Área	7	delete_area
28	Can view Área	7	view_area
29	Can add Bien	8	add_bien
30	Can change Bien	8	change_bien
31	Can delete Bien	8	delete_bien
32	Can view Bien	8	view_bien
33	Can add Orden de Compra	9	add_ordencompra
34	Can change Orden de Compra	9	change_ordencompra
35	Can delete Orden de Compra	9	delete_ordencompra
36	Can view Orden de Compra	9	view_ordencompra
37	Can add Sede	10	add_sede
38	Can change Sede	10	change_sede
39	Can delete Sede	10	delete_sede
40	Can view Sede	10	view_sede
41	Can add Asignación	11	add_asignacion
42	Can change Asignación	11	change_asignacion
43	Can delete Asignación	11	delete_asignacion
44	Can view Asignación	11	view_asignacion
45	Can add Trazabilidad de Movimiento	12	add_trazabilidadmovimientos
46	Can change Trazabilidad de Movimiento	12	change_trazabilidadmovimientos
47	Can delete Trazabilidad de Movimiento	12	delete_trazabilidadmovimientos
48	Can view Trazabilidad de Movimiento	12	view_trazabilidadmovimientos
49	Can add Mantenimiento de Bien	13	add_mantenimientobien
50	Can change Mantenimiento de Bien	13	change_mantenimientobien
51	Can delete Mantenimiento de Bien	13	delete_mantenimientobien
52	Can view Mantenimiento de Bien	13	view_mantenimientobien
53	Can add Log de Bien	14	add_logbien
54	Can change Log de Bien	14	change_logbien
55	Can delete Log de Bien	14	delete_logbien
56	Can view Log de Bien	14	view_logbien
57	Can add Log de Acceso y Seguridad	15	add_logacceso
58	Can change Log de Acceso y Seguridad	15	change_logacceso
59	Can delete Log de Acceso y Seguridad	15	delete_logacceso
60	Can view Log de Acceso y Seguridad	15	view_logacceso
61	Can add Automotor	16	add_automotor
62	Can change Automotor	16	change_automotor
63	Can delete Automotor	16	delete_automotor
64	Can view Automotor	16	view_automotor
65	Can add Inmueble	17	add_inmueble
66	Can change Inmueble	17	change_inmueble
67	Can delete Inmueble	17	delete_inmueble
68	Can view Inmueble	17	view_inmueble
\.


--
-- Data for Name: automotor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.automotor (bien_ptr_id, placa, marca, modelo, anio, color, serial_motor, serial_carroceria) FROM stdin;
1	fgf	rgrgr	rgrg	2026	rgrg	rgrg	rgrg
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	users	customuser
7	inventario	area
8	inventario	bien
9	inventario	ordencompra
10	inventario	sede
11	inventario	asignacion
12	inventario	trazabilidadmovimientos
13	inventario	mantenimientobien
14	auditoria	logbien
15	auditoria	logacceso
16	automotor	automotor
17	inmuebles	inmueble
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	inventario	0001_initial	2026-07-30 07:28:17.385389-04
2	contenttypes	0001_initial	2026-07-30 07:28:17.401895-04
3	contenttypes	0002_remove_content_type_name	2026-07-30 07:28:17.427087-04
4	auth	0001_initial	2026-07-30 07:28:17.47206-04
5	auth	0002_alter_permission_name_max_length	2026-07-30 07:28:17.481035-04
6	auth	0003_alter_user_email_max_length	2026-07-30 07:28:17.487018-04
7	auth	0004_alter_user_username_opts	2026-07-30 07:28:17.494001-04
8	auth	0005_alter_user_last_login_null	2026-07-30 07:28:17.498986-04
9	auth	0006_require_contenttypes_0002	2026-07-30 07:28:17.49999-04
10	auth	0007_alter_validators_add_error_messages	2026-07-30 07:28:17.505967-04
11	auth	0008_alter_user_username_max_length	2026-07-30 07:28:17.510546-04
12	auth	0009_alter_user_last_name_max_length	2026-07-30 07:28:17.514557-04
13	auth	0010_alter_group_name_max_length	2026-07-30 07:28:17.522594-04
14	auth	0011_update_proxy_permissions	2026-07-30 07:28:17.528824-04
15	auth	0012_alter_user_first_name_max_length	2026-07-30 07:28:17.531816-04
16	users	0001_initial	2026-07-30 07:28:17.582403-04
17	admin	0001_initial	2026-07-30 07:28:17.608349-04
18	admin	0002_logentry_remove_auto_add	2026-07-30 07:28:17.614335-04
19	admin	0003_logentry_add_action_flag_choices	2026-07-30 07:28:17.621887-04
20	auditoria	0001_initial	2026-07-30 07:28:17.62937-04
21	auditoria	0002_initial	2026-07-30 07:28:17.637435-04
22	auditoria	0003_initial	2026-07-30 07:28:17.648173-04
23	auditoria	0004_logacceso	2026-07-30 07:28:17.666137-04
24	inventario	0002_initial	2026-07-30 07:28:17.720487-04
25	inventario	0003_ordencompra_archivo_documento	2026-07-30 07:28:17.720487-04
26	inventario	0004_bien_tasa_bcv_compra_bien_valor_adquisicion_and_more	2026-07-30 07:28:17.802932-04
27	automotor	0001_initial	2026-07-30 07:28:17.822143-04
28	automotor	0002_rename_año_automotor_anio	2026-07-30 07:28:17.836242-04
29	inmuebles	0001_initial	2026-07-30 07:28:17.869796-04
30	inventario	0005_ordencompra_proveedor	2026-07-30 07:28:17.869796-04
31	inventario	0006_mantenimientobien	2026-07-30 07:28:17.904318-04
32	sessions	0001_initial	2026-07-30 07:28:17.917485-04
33	users	0002_alter_customuser_rol	2026-07-30 07:28:17.927773-04
34	users	0003_alter_customuser_table	2026-07-30 07:28:17.938888-04
35	users	0004_customuser_reset_code_and_more	2026-07-30 07:28:17.959507-04
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: inmueble; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inmueble (bien_ptr_id, direccion_completa, registro_propiedad, area_terreno, area_construccion, catastro) FROM stdin;
8	caracas	prueba	1000.00	3000.00	prueba
\.


--
-- Data for Name: inventario_area; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario_area (id, nombre, sede_id) FROM stdin;
1	Dirección General	1
2	Recursos Humanos	1
3	Administración y Finanzas	1
4	Tecnología de Información	1
5	Servicios Generales	1
6	Seguridad	1
\.


--
-- Data for Name: inventario_asignacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario_asignacion (id, fecha_asignacion, activa, area_id, usuario_id, bien_id) FROM stdin;
1	2026-07-30 09:26:38.648588-04	f	2	2	8
3	2026-07-30 10:01:19.770849-04	t	2	2	8
2	2026-07-30 10:00:53.93627-04	f	2	2	8
\.


--
-- Data for Name: inventario_bien; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario_bien (id, nombre, descripcion, serial_fabrica, codigo_inventario, estado, orden_compra_id, sede_id, tasa_bcv_compra, valor_adquisicion, valor_adquisicion_bs) FROM stdin;
1	rgrgr rgrg (fgf)	Automotor de la DEM. Placa: fgf. Motor: rgrg. Color: rgrg.		DEM-VEH-35062	ACTIVO	\N	1	1.0000	2000.00	0.00
8	Inmueble Catastro: prueba	Bien Inmueble de la DEM. Ficha Catastral: prueba. Registro: prueba. Área Terreno: 1000m²	\N	DEM-INM-5716	ACTIVO	\N	1	1.0000	2000.00	0.00
9	silla	fhfhfhf	44545	hhhh	INACTIVO	\N	1	1.0000	0.00	0.00
\.


--
-- Data for Name: inventario_mantenimientobien; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario_mantenimientobien (id, numero_ficha, fecha_ficha, tipo_mantenimiento, actividad_realizada, materiales_empleados, numero_factura, costo, fecha_mantenimiento, nota, reparado_por, conformado_por, responsable_administrativo, bien_id) FROM stdin;
1	MANT-8492	2026-07-30	CORRECTIVO	Limpieza física general, reemplazo de partes dañadas y pruebas de operatividad.	Alcohol isopropílico, herramientas de precisión, pasta térmica.	Autogestión	0.00	2026-07-30	Pruebas de funcionamiento post-servicio aprobadas al 100%.	Ing. Pedro Pérez (Soporte Técnico)	María González (Jefe de Bienes DEM)	Director de Administración DEM	8
\.


--
-- Data for Name: inventario_ordencompra; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario_ordencompra (id, numero_orden, fecha_llegada, conformidad_recepcion, archivo_documento, proveedor) FROM stdin;
1	45677890	2026-07-30	f	ordenes_compra/HORARIO_NOCTURNO_2025_2026_JOSE_PEREZ_30850141.pdf	DEM
\.


--
-- Data for Name: inventario_sede; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario_sede (id, nombre) FROM stdin;
1	Sede Principal DEM
\.


--
-- Data for Name: inventario_trazabilidadmovimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario_trazabilidadmovimientos (id, tipo_movimiento, fecha, motivo, area_destino_id, area_origen_id, bien_id, sede_destino_id, sede_origen_id, usuario_destino_id, usuario_origen_id, usuario_responsable_id) FROM stdin;
1	ASIGNACION	2026-07-30 09:26:38.765908-04	Asignación de bien público al operador Diego Figueroa en el área Recursos Humanos.	2	\N	8	1	\N	2	\N	\N
2	INCORPORACION	2026-07-30 09:58:07.753253-04	Incorporación inicial de bien público en el inventario.	\N	\N	9	1	\N	\N	\N	\N
3	ASIGNACION	2026-07-30 10:00:53.96961-04	Asignación de bien público al operador Diego Figueroa en el área Recursos Humanos.	2	\N	8	1	\N	2	\N	\N
4	ASIGNACION	2026-07-30 10:01:19.770849-04	Asignación de bien público al operador Diego Figueroa en el área Recursos Humanos.	2	\N	8	1	\N	2	\N	\N
\.


--
-- Data for Name: log_acceso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.log_acceso (id, ip_address, accion, fecha, detalles, usuario_id) FROM stdin;
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, cedula, cargo, rol, unidad_pertenencia_id, reset_code, reset_code_created_at) FROM stdin;
3	pbkdf2_sha256$1000000$XVaM5BLdsP0xam1cxto8Nh$5D5GsALVEuCvA46EoQzvFyjJc/Y2C8kXs/iH0YmgtJE=	\N	f	operador			operador@example.com	f	t	2026-07-30 07:56:03.655656-04	V-22222222	\N	OPERADOR	\N	\N	\N
4	pbkdf2_sha256$1000000$WXkqJKhqXW2wq9sVlpxtiY$vFHPsLUJQaWMM8eHYa3OTpnYu0Hx4biUSBrlU0K8CCM=	\N	f	auditor			auditor@example.com	f	t	2026-07-30 07:56:03.672372-04	V-33333333	\N	AUDITOR	\N	\N	\N
1	pbkdf2_sha256$1000000$0T4SmQKn2psbrcRvmLWKwb$JsnSSOK6L/hpZV0EsPLiwRXnpcOrE/K8PD2Qda23If4=	\N	t	admin			admin@gmail.com	t	t	2026-07-30 07:30:12.60251-04		\N	ADMINISTRADOR	\N	\N	\N
2	pbkdf2_sha256$1000000$wZyWhQ1KM26LBxdIfRcrKm$jAokIWAsrTcGhHvD77MSk1FnS0HVBxMxQ5uInkkf1+0=	\N	f	martidiaz	Diego	Figueroa	diego@gmail.com	f	t	2026-07-30 08:04:58.706338-04	V-31071910	Analista Profesional III	ADMINISTRADOR	\N	\N	\N
\.


--
-- Data for Name: usuario_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: usuario_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Name: auditoria_logbien_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auditoria_logbien_id_seq', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: custom_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.custom_user_groups_id_seq', 1, false);


--
-- Name: custom_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.custom_user_id_seq', 2, true);


--
-- Name: custom_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.custom_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 35, true);


--
-- Name: inventario_area_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_area_id_seq', 6, true);


--
-- Name: inventario_asignacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_asignacion_id_seq', 3, true);


--
-- Name: inventario_bien_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_bien_id_seq', 9, true);


--
-- Name: inventario_mantenimientobien_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_mantenimientobien_id_seq', 1, true);


--
-- Name: inventario_ordencompra_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_ordencompra_id_seq', 1, true);


--
-- Name: inventario_sede_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_sede_id_seq', 1, true);


--
-- Name: inventario_trazabilidadmovimientos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_trazabilidadmovimientos_id_seq', 4, true);


--
-- Name: log_acceso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.log_acceso_id_seq', 1, false);


--
-- Name: auditoria_logbien auditoria_logbien_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria_logbien
    ADD CONSTRAINT auditoria_logbien_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: automotor automotor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.automotor
    ADD CONSTRAINT automotor_pkey PRIMARY KEY (bien_ptr_id);


--
-- Name: automotor automotor_placa_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.automotor
    ADD CONSTRAINT automotor_placa_key UNIQUE (placa);


--
-- Name: automotor automotor_serial_carroceria_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.automotor
    ADD CONSTRAINT automotor_serial_carroceria_key UNIQUE (serial_carroceria);


--
-- Name: automotor automotor_serial_motor_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.automotor
    ADD CONSTRAINT automotor_serial_motor_key UNIQUE (serial_motor);


--
-- Name: usuario custom_user_cedula_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT custom_user_cedula_key UNIQUE (cedula);


--
-- Name: usuario_groups custom_user_groups_customuser_id_group_id_ea14f886_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_groups
    ADD CONSTRAINT custom_user_groups_customuser_id_group_id_ea14f886_uniq UNIQUE (customuser_id, group_id);


--
-- Name: usuario_groups custom_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_groups
    ADD CONSTRAINT custom_user_groups_pkey PRIMARY KEY (id);


--
-- Name: usuario custom_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT custom_user_pkey PRIMARY KEY (id);


--
-- Name: usuario_user_permissions custom_user_user_permiss_customuser_id_permission_f9232336_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_user_permissions
    ADD CONSTRAINT custom_user_user_permiss_customuser_id_permission_f9232336_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: usuario_user_permissions custom_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_user_permissions
    ADD CONSTRAINT custom_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: usuario custom_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT custom_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: inmueble inmueble_catastro_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inmueble
    ADD CONSTRAINT inmueble_catastro_key UNIQUE (catastro);


--
-- Name: inmueble inmueble_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inmueble
    ADD CONSTRAINT inmueble_pkey PRIMARY KEY (bien_ptr_id);


--
-- Name: inmueble inmueble_registro_propiedad_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inmueble
    ADD CONSTRAINT inmueble_registro_propiedad_key UNIQUE (registro_propiedad);


--
-- Name: inventario_area inventario_area_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_area
    ADD CONSTRAINT inventario_area_pkey PRIMARY KEY (id);


--
-- Name: inventario_asignacion inventario_asignacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_asignacion
    ADD CONSTRAINT inventario_asignacion_pkey PRIMARY KEY (id);


--
-- Name: inventario_bien inventario_bien_codigo_inventario_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_bien
    ADD CONSTRAINT inventario_bien_codigo_inventario_key UNIQUE (codigo_inventario);


--
-- Name: inventario_bien inventario_bien_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_bien
    ADD CONSTRAINT inventario_bien_pkey PRIMARY KEY (id);


--
-- Name: inventario_bien inventario_bien_serial_fabrica_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_bien
    ADD CONSTRAINT inventario_bien_serial_fabrica_key UNIQUE (serial_fabrica);


--
-- Name: inventario_mantenimientobien inventario_mantenimientobien_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_mantenimientobien
    ADD CONSTRAINT inventario_mantenimientobien_pkey PRIMARY KEY (id);


--
-- Name: inventario_ordencompra inventario_ordencompra_numero_orden_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_ordencompra
    ADD CONSTRAINT inventario_ordencompra_numero_orden_key UNIQUE (numero_orden);


--
-- Name: inventario_ordencompra inventario_ordencompra_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_ordencompra
    ADD CONSTRAINT inventario_ordencompra_pkey PRIMARY KEY (id);


--
-- Name: inventario_sede inventario_sede_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_sede
    ADD CONSTRAINT inventario_sede_pkey PRIMARY KEY (id);


--
-- Name: inventario_trazabilidadmovimientos inventario_trazabilidadmovimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_trazabilidadmovimientos
    ADD CONSTRAINT inventario_trazabilidadmovimientos_pkey PRIMARY KEY (id);


--
-- Name: log_acceso log_acceso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_acceso
    ADD CONSTRAINT log_acceso_pkey PRIMARY KEY (id);


--
-- Name: auditoria_logbien_bien_id_3b4afbe5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auditoria_logbien_bien_id_3b4afbe5 ON public.auditoria_logbien USING btree (bien_id);


--
-- Name: auditoria_logbien_usuario_id_1d31e034; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auditoria_logbien_usuario_id_1d31e034 ON public.auditoria_logbien USING btree (usuario_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: automotor_placa_eb100448_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX automotor_placa_eb100448_like ON public.automotor USING btree (placa varchar_pattern_ops);


--
-- Name: automotor_serial_carroceria_72f31f2d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX automotor_serial_carroceria_72f31f2d_like ON public.automotor USING btree (serial_carroceria varchar_pattern_ops);


--
-- Name: automotor_serial_motor_150610ac_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX automotor_serial_motor_150610ac_like ON public.automotor USING btree (serial_motor varchar_pattern_ops);


--
-- Name: custom_user_cedula_72be85f3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX custom_user_cedula_72be85f3_like ON public.usuario USING btree (cedula varchar_pattern_ops);


--
-- Name: custom_user_groups_customuser_id_8e3d0338; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX custom_user_groups_customuser_id_8e3d0338 ON public.usuario_groups USING btree (customuser_id);


--
-- Name: custom_user_groups_group_id_02874f21; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX custom_user_groups_group_id_02874f21 ON public.usuario_groups USING btree (group_id);


--
-- Name: custom_user_unidad_pertenencia_id_fff76899; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX custom_user_unidad_pertenencia_id_fff76899 ON public.usuario USING btree (unidad_pertenencia_id);


--
-- Name: custom_user_user_permissions_customuser_id_ec2da4cb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX custom_user_user_permissions_customuser_id_ec2da4cb ON public.usuario_user_permissions USING btree (customuser_id);


--
-- Name: custom_user_user_permissions_permission_id_f82b5e3f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX custom_user_user_permissions_permission_id_f82b5e3f ON public.usuario_user_permissions USING btree (permission_id);


--
-- Name: custom_user_username_5f1e8aad_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX custom_user_username_5f1e8aad_like ON public.usuario USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: inmueble_catastro_403387aa_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inmueble_catastro_403387aa_like ON public.inmueble USING btree (catastro varchar_pattern_ops);


--
-- Name: inmueble_registro_propiedad_79c1cbbe_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inmueble_registro_propiedad_79c1cbbe_like ON public.inmueble USING btree (registro_propiedad varchar_pattern_ops);


--
-- Name: inventario_area_sede_id_8f318905; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_area_sede_id_8f318905 ON public.inventario_area USING btree (sede_id);


--
-- Name: inventario_asignacion_area_id_5d510b8f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_asignacion_area_id_5d510b8f ON public.inventario_asignacion USING btree (area_id);


--
-- Name: inventario_asignacion_bien_id_0bdac784; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_asignacion_bien_id_0bdac784 ON public.inventario_asignacion USING btree (bien_id);


--
-- Name: inventario_asignacion_usuario_id_226b8b7c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_asignacion_usuario_id_226b8b7c ON public.inventario_asignacion USING btree (usuario_id);


--
-- Name: inventario_bien_codigo_inventario_c781896f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_bien_codigo_inventario_c781896f_like ON public.inventario_bien USING btree (codigo_inventario varchar_pattern_ops);


--
-- Name: inventario_bien_orden_compra_id_af84bd6e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_bien_orden_compra_id_af84bd6e ON public.inventario_bien USING btree (orden_compra_id);


--
-- Name: inventario_bien_sede_id_717d44dc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_bien_sede_id_717d44dc ON public.inventario_bien USING btree (sede_id);


--
-- Name: inventario_bien_serial_fabrica_344607f9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_bien_serial_fabrica_344607f9_like ON public.inventario_bien USING btree (serial_fabrica varchar_pattern_ops);


--
-- Name: inventario_mantenimientobien_bien_id_8eadc112; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_mantenimientobien_bien_id_8eadc112 ON public.inventario_mantenimientobien USING btree (bien_id);


--
-- Name: inventario_ordencompra_numero_orden_c1834d90_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_ordencompra_numero_orden_c1834d90_like ON public.inventario_ordencompra USING btree (numero_orden varchar_pattern_ops);


--
-- Name: inventario_trazabilidadmov_usuario_responsable_id_2856ab1f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_trazabilidadmov_usuario_responsable_id_2856ab1f ON public.inventario_trazabilidadmovimientos USING btree (usuario_responsable_id);


--
-- Name: inventario_trazabilidadmovimientos_area_destino_id_198db076; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_trazabilidadmovimientos_area_destino_id_198db076 ON public.inventario_trazabilidadmovimientos USING btree (area_destino_id);


--
-- Name: inventario_trazabilidadmovimientos_area_origen_id_906985fa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_trazabilidadmovimientos_area_origen_id_906985fa ON public.inventario_trazabilidadmovimientos USING btree (area_origen_id);


--
-- Name: inventario_trazabilidadmovimientos_bien_id_9a3e2985; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_trazabilidadmovimientos_bien_id_9a3e2985 ON public.inventario_trazabilidadmovimientos USING btree (bien_id);


--
-- Name: inventario_trazabilidadmovimientos_sede_destino_id_c515c919; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_trazabilidadmovimientos_sede_destino_id_c515c919 ON public.inventario_trazabilidadmovimientos USING btree (sede_destino_id);


--
-- Name: inventario_trazabilidadmovimientos_sede_origen_id_90383ca6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_trazabilidadmovimientos_sede_origen_id_90383ca6 ON public.inventario_trazabilidadmovimientos USING btree (sede_origen_id);


--
-- Name: inventario_trazabilidadmovimientos_usuario_destino_id_1aeeb76d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_trazabilidadmovimientos_usuario_destino_id_1aeeb76d ON public.inventario_trazabilidadmovimientos USING btree (usuario_destino_id);


--
-- Name: inventario_trazabilidadmovimientos_usuario_origen_id_33f5b2f5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_trazabilidadmovimientos_usuario_origen_id_33f5b2f5 ON public.inventario_trazabilidadmovimientos USING btree (usuario_origen_id);


--
-- Name: log_acceso_usuario_id_570f3b67; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX log_acceso_usuario_id_570f3b67 ON public.log_acceso USING btree (usuario_id);


--
-- Name: auditoria_logbien auditoria_logbien_bien_id_3b4afbe5_fk_inventario_bien_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria_logbien
    ADD CONSTRAINT auditoria_logbien_bien_id_3b4afbe5_fk_inventario_bien_id FOREIGN KEY (bien_id) REFERENCES public.inventario_bien(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auditoria_logbien auditoria_logbien_usuario_id_1d31e034_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria_logbien
    ADD CONSTRAINT auditoria_logbien_usuario_id_1d31e034_fk_custom_user_id FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: automotor automotor_bien_ptr_id_056b404d_fk_inventario_bien_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.automotor
    ADD CONSTRAINT automotor_bien_ptr_id_056b404d_fk_inventario_bien_id FOREIGN KEY (bien_ptr_id) REFERENCES public.inventario_bien(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuario_groups custom_user_groups_customuser_id_8e3d0338_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_groups
    ADD CONSTRAINT custom_user_groups_customuser_id_8e3d0338_fk_custom_user_id FOREIGN KEY (customuser_id) REFERENCES public.usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuario_groups custom_user_groups_group_id_02874f21_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_groups
    ADD CONSTRAINT custom_user_groups_group_id_02874f21_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuario custom_user_unidad_pertenencia_i_fff76899_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT custom_user_unidad_pertenencia_i_fff76899_fk_inventari FOREIGN KEY (unidad_pertenencia_id) REFERENCES public.inventario_area(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuario_user_permissions custom_user_user_per_customuser_id_ec2da4cb_fk_custom_us; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_user_permissions
    ADD CONSTRAINT custom_user_user_per_customuser_id_ec2da4cb_fk_custom_us FOREIGN KEY (customuser_id) REFERENCES public.usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuario_user_permissions custom_user_user_per_permission_id_f82b5e3f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_user_permissions
    ADD CONSTRAINT custom_user_user_per_permission_id_f82b5e3f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_custom_user_id FOREIGN KEY (user_id) REFERENCES public.usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inmueble inmueble_bien_ptr_id_f84646c0_fk_inventario_bien_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inmueble
    ADD CONSTRAINT inmueble_bien_ptr_id_f84646c0_fk_inventario_bien_id FOREIGN KEY (bien_ptr_id) REFERENCES public.inventario_bien(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_area inventario_area_sede_id_8f318905_fk_inventario_sede_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_area
    ADD CONSTRAINT inventario_area_sede_id_8f318905_fk_inventario_sede_id FOREIGN KEY (sede_id) REFERENCES public.inventario_sede(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_asignacion inventario_asignacion_area_id_5d510b8f_fk_inventario_area_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_asignacion
    ADD CONSTRAINT inventario_asignacion_area_id_5d510b8f_fk_inventario_area_id FOREIGN KEY (area_id) REFERENCES public.inventario_area(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_asignacion inventario_asignacion_bien_id_0bdac784_fk_inventario_bien_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_asignacion
    ADD CONSTRAINT inventario_asignacion_bien_id_0bdac784_fk_inventario_bien_id FOREIGN KEY (bien_id) REFERENCES public.inventario_bien(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_asignacion inventario_asignacion_usuario_id_226b8b7c_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_asignacion
    ADD CONSTRAINT inventario_asignacion_usuario_id_226b8b7c_fk_custom_user_id FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_bien inventario_bien_orden_compra_id_af84bd6e_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_bien
    ADD CONSTRAINT inventario_bien_orden_compra_id_af84bd6e_fk_inventari FOREIGN KEY (orden_compra_id) REFERENCES public.inventario_ordencompra(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_bien inventario_bien_sede_id_717d44dc_fk_inventario_sede_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_bien
    ADD CONSTRAINT inventario_bien_sede_id_717d44dc_fk_inventario_sede_id FOREIGN KEY (sede_id) REFERENCES public.inventario_sede(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_mantenimientobien inventario_mantenimi_bien_id_8eadc112_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_mantenimientobien
    ADD CONSTRAINT inventario_mantenimi_bien_id_8eadc112_fk_inventari FOREIGN KEY (bien_id) REFERENCES public.inventario_bien(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_trazabilidadmovimientos inventario_trazabili_area_destino_id_198db076_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_trazabilidadmovimientos
    ADD CONSTRAINT inventario_trazabili_area_destino_id_198db076_fk_inventari FOREIGN KEY (area_destino_id) REFERENCES public.inventario_area(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_trazabilidadmovimientos inventario_trazabili_area_origen_id_906985fa_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_trazabilidadmovimientos
    ADD CONSTRAINT inventario_trazabili_area_origen_id_906985fa_fk_inventari FOREIGN KEY (area_origen_id) REFERENCES public.inventario_area(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_trazabilidadmovimientos inventario_trazabili_bien_id_9a3e2985_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_trazabilidadmovimientos
    ADD CONSTRAINT inventario_trazabili_bien_id_9a3e2985_fk_inventari FOREIGN KEY (bien_id) REFERENCES public.inventario_bien(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_trazabilidadmovimientos inventario_trazabili_sede_destino_id_c515c919_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_trazabilidadmovimientos
    ADD CONSTRAINT inventario_trazabili_sede_destino_id_c515c919_fk_inventari FOREIGN KEY (sede_destino_id) REFERENCES public.inventario_sede(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_trazabilidadmovimientos inventario_trazabili_sede_origen_id_90383ca6_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_trazabilidadmovimientos
    ADD CONSTRAINT inventario_trazabili_sede_origen_id_90383ca6_fk_inventari FOREIGN KEY (sede_origen_id) REFERENCES public.inventario_sede(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_trazabilidadmovimientos inventario_trazabili_usuario_destino_id_1aeeb76d_fk_custom_us; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_trazabilidadmovimientos
    ADD CONSTRAINT inventario_trazabili_usuario_destino_id_1aeeb76d_fk_custom_us FOREIGN KEY (usuario_destino_id) REFERENCES public.usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_trazabilidadmovimientos inventario_trazabili_usuario_origen_id_33f5b2f5_fk_custom_us; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_trazabilidadmovimientos
    ADD CONSTRAINT inventario_trazabili_usuario_origen_id_33f5b2f5_fk_custom_us FOREIGN KEY (usuario_origen_id) REFERENCES public.usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_trazabilidadmovimientos inventario_trazabili_usuario_responsable__2856ab1f_fk_custom_us; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_trazabilidadmovimientos
    ADD CONSTRAINT inventario_trazabili_usuario_responsable__2856ab1f_fk_custom_us FOREIGN KEY (usuario_responsable_id) REFERENCES public.usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: log_acceso log_acceso_usuario_id_570f3b67_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_acceso
    ADD CONSTRAINT log_acceso_usuario_id_570f3b67_fk_custom_user_id FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

