# Generated by Django 5.2.12 on 2026-04-28 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='inventario.bien'),
        ),
        migrations.AddField(
            model_name='bien',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='inventario.ordencompra'),
        ),
        migrations.AddField(
            model_name='bien',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.sede'),
        ),
        migrations.AddField(
            model_name='area',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.sede'),
        ),
    ]
