# Generated by Django 5.2.12 on 2026-05-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='archivo_documento',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/'),
        ),
    ]
