# Generated by Django 5.2.12 on 2026-05-29 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_ordencompra_archivo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='tasa_bcv_compra',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tasa BCV de Compra'),
        ),
        migrations.AddField(
            model_name='bien',
            name='valor_adquisicion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de Adquisición ($)'),
        ),
        migrations.AddField(
            model_name='bien',
            name='valor_adquisicion_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor de Adquisición (Bs)'),
        ),
        migrations.CreateModel(
            name='TrazabilidadMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INCORPORACION', 'Incorporación'), ('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación'), ('DESINCORPORACION', 'Desincorporación')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('area_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_area_destino', to='inventario.area')),
                ('area_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_area_origen', to='inventario.area')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazas', to='inventario.bien')),
                ('sede_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_destino', to='inventario.sede')),
                ('sede_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_origen', to='inventario.sede')),
                ('usuario_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_usuario_destino', to=settings.AUTH_USER_MODEL)),
                ('usuario_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_usuario_origen', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trazabilidad de Movimiento',
                'verbose_name_plural': 'Trazabilidades de Movimientos',
            },
        ),
    ]
