# Generated by Django 5.2.12 on 2026-06-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_bien_tasa_bcv_compra_bien_valor_adquisicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.CharField(default='Dirección Ejecutiva de la Magistratura (DEM)', max_length=150, verbose_name='Proveedor o Ente Donante'),
        ),
    ]
