# Generated by Django 5.2.12 on 2026-06-05 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_ordencompra_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(max_length=50, verbose_name='Número de Ficha/Reporte')),
                ('fecha_ficha', models.DateField(verbose_name='Fecha de la Ficha')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], default='CORRECTIVO', max_length=20)),
                ('actividad_realizada', models.TextField(verbose_name='Actividad Realizada')),
                ('materiales_empleados', models.TextField(blank=True, null=True, verbose_name='Materiales Empleados')),
                ('numero_factura', models.CharField(default='Autogestión', max_length=100, verbose_name='Número de Factura')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo (Bs/$)')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha del Mantenimiento')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Notas/Observaciones')),
                ('reparado_por', models.CharField(max_length=150, verbose_name='Reparado por')),
                ('conformado_por', models.CharField(max_length=150, verbose_name='Conformado por')),
                ('responsable_administrativo', models.CharField(max_length=150, verbose_name='Responsable Administrativo')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.bien')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Bien',
                'verbose_name_plural': 'Mantenimientos de Bienes',
            },
        ),
    ]
