# Generated by Django 5.2.12 on 2026-08-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_mantenimientobien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='trazabilidadmovimientos',
            name='usuario_destino',
        ),
        migrations.RemoveField(
            model_name='trazabilidadmovimientos',
            name='usuario_origen',
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.area')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='inventario.funcionario'),
        ),
        migrations.AddField(
            model_name='trazabilidadmovimientos',
            name='funcionario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_funcionario_destino', to='inventario.funcionario'),
        ),
        migrations.AddField(
            model_name='trazabilidadmovimientos',
            name='funcionario_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_funcionario_origen', to='inventario.funcionario'),
        ),
    ]
