# Generated by Django 5.2.12 on 2026-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_asignacion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='¿Oficina activa?'),
        ),
        migrations.AddField(
            model_name='area',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código interno (Convalidación de Oficinas)'),
        ),
        migrations.AddField(
            model_name='area',
            name='direccion_general',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección/Unidad General a la que pertenece'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
