# Generated by Django 5.2.12 on 2026-08-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_area_activa_area_codigo_area_direccion_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='archivo_documento',
            field=models.FileField(default='', upload_to='ordenes_compra/', verbose_name='Documento de la Orden de Compra (soporte)'),
            preserve_default=False,
        ),
    ]
