# Generated by Django 5.2.12 on 2026-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_ordencompra_archivo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='categoria',
            field=models.CharField(blank=True, choices=[('COMPUTADORA', 'Computadora / Equipo de Computación'), ('PANTALLA', 'Pantalla / Monitor'), ('PERIFERICO', 'Periférico (Mouse, Teclado, etc.)'), ('MOBILIARIO', 'Mobiliario (Escritorio, Silla, Archivador)'), ('EQUIPO_OFICINA', 'Equipo de Oficina (Impresora, Fotocopiadora)'), ('ELECTRODOMESTICO', 'Electrodoméstico'), ('HERRAMIENTA', 'Herramienta / Equipo Técnico'), ('OTRO', 'Otro')], max_length=30, null=True, verbose_name='Categoría del Bien Mueble'),
        ),
    ]
