# Generated by Django 5.2.12 on 2026-09-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_bien_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='bien',
            name='color_mueble',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='bien',
            name='componente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='bien',
            name='marca_componente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del Componente'),
        ),
        migrations.AddField(
            model_name='bien',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='bien',
            name='modelo_componente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo del Componente'),
        ),
        migrations.AddField(
            model_name='bien',
            name='serial_componente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial del Componente'),
        ),
    ]
