# Generated by Django 5.2.12 on 2026-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_bien_caracteristicas_bien_color_mueble_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición'),
        ),
    ]
